### ISSUE TITLE
drop event?

### ISSUE THREAD

**Issue by tapchicovua** [ajax333221/isepic-chess#25]
Are there any similar events?
drop event? Fires when a piece is dropped?
Is there an event that is triggered after moving a piece to be able to return to the original position and compare the purpose of the move?

**Comment by ajax333221** [comment]
Events like this are not yet implemented ( https://github.com/ajax333221/isepic-chess-ui/issues/6 )

It can be done only by modifying the .js file, for the drop event one would need to modify the **isepic-chess-ui.js**, lines:

https://github.com/ajax333221/isepic-chess-ui/blob/9ed48c229968bc7590344f83dc2684fdc559f447/js/isepic-chess-ui.js#L493-L533

In `doc.off("mouseup.icuirelease").on("mouseup.icuirelease", function(e){ ... }` the line `_playMoveCaller.apply(board, [[old_drg, current_bos], true]);` should return the move object when a move is successfully played, otherwise it seems the value can be either Boolean _false_ when _playMoveCaller() is not successful or the value _null_ when the inner playMove() is not successful.

I know modifying the library itself is cumbersome, because updating it would erase the changes you make to it and things like that, but for now it's the only way until events are implemented.

**Comment by tapchicovua** [comment]
Thank you for your feedback


Vào Th 3, 5 thg 10, 2021 vào lúc 22:04 Ajax Isepic <
***@***.***> đã viết:
