### ISSUE TITLE
En passant should not be inlcuded in the FEN when it is not possible to execute it next turn.

### ISSUE THREAD

**Issue by ajax333221** [ajax333221/Isepic-Chess#27]
While it looks like it is perfectly fine and even the specs kind of say it is permitted:

```
Therefore, an en passant target square field may have
a square name even if there is no pawn of the opposing side that may
immediately execute the en passant capture.
```

A fun scenario could happen with threefold repetition, it is not very clear if one should take this into consideration or not, but after some reading:

```
"... occupy the same squares and the possible moves of all the pieces of both players are the same."
```

https://chess.stackexchange.com/questions/22970/fide-threefold-repetition-and-possible-moves

And confirming this with how Lichess implemented this:

![111](https://user-images.githubusercontent.com/1434803/138515990-9b8048e3-4270-43d5-a9f3-a209d0d7452f.png)

**Note:** in Lichess you can draw with **34... Kc8**, and a bad implementation would not allow this at that point (**Ic.js** currently doesn't detect that move as a draw).

I will tag it as a _bug_ because it feels like it is wrongfully implemented as it is now.

**Comment by Daar543** [comment]
Technically, there are 3 "restrictions" when the ep square can be written:

1) Any time after a double move (general)
2) Only if there is a pawn available to capture (pseudo-legal)
3) Only if the capture is legal move (legal)

I have heard that some implementations take the first option, in which case it is never sufficient for FEN strings to just be compared for draw by repetition. 

The option #3 would need to consider all checks after succesful capture, which might be unnecessary slowdown when generating moves and positions. In some cases, a better option seems to use #1 or #2 and then just lazily evaluate if all possible EP moves are actually legal, when the positions are otherwise same.
