### ISSUE TITLE
How to undo “MockMove”

### ISSUE THREAD

**Issue by user1704** [ajax333221/isepic-chess#37]

**Comment by ajax333221** [comment]
Hi, it is true there isn't many examples of this, I will eventually add a "How to use MockMoves?" to the Docs, but for now I will try to explain it below:

There are 3 board methods that use this p option:

- `board.playRandomMove(p)`
- `board.playMove(mov, p)`
- `board.playMoves(movArray, p)`

You enable the option like this:

- `board.playRandomMove({isMockMove: true})`
- `board.playMove("e4", {isMockMove: true})`
- `board.playMoves(["e4", "e5"], {isMockMove: true}) //note §`

`§ note: in b.playMoves(...) each move will be mock move, so e4 will be reversed by the time e5 is played, and because this function returns a Boolean of "all moves were played?" this will be false. While passing something like ["c3", "Nc3", "c2"] with all of the moves from the same side instead of alternating between active and non-active sides, will be a hacky way to have all these moves tested if they are legal moves or not, returning true only if all of them are legal moves for the side to move.`

What will happen is that, the board will be unchanged (no move will be sent), but you get the returned value as if it went through.

For `board.playRandomMove(...)` and `board.playMove(...)` where a _move (Object)_ is returned, it will always be unreferenced when using **isMockMove**, so there is no need to use **isUnreferenced** when working with mock moves.
